module.export =  {  
    "version":2,
    "query":"java",
    "location":"austin, tx",
    "dupefilter":true,
    "highlight":false,
    "radius":25,
    "start":1,
    "end":10,
    "totalResults":547,
    "pageNumber":0,
    "results":[  
        {  
            "jobtitle":"Java Developer",
            "company":"XYZ Corp",
            "city":"Austin",
            "state":"TX",
            "country":"US",
            "formattedLocation":"Austin, TX",
            "source":"Dice",
            "date":"Mon, 02 Aug 2017 16:21:00 GMT",
            "snippet": `looking for an object-oriented Java Developer... Java Servlets,
              HTML, JavaScript, AJAX, Struts, Struts2, JSF) desirable. Familiarity with
              Tomcat and the Java...`,
            "url":"http://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203",
            "onmousedown":"indeed_clk(this, '0000');",
            "latitude":30.27127,
            "longitude":-97.74103,
            "jobkey":"12345",
            "sponsored":false,
            "expired":false,
            "indeedApply":true,
            "formattedLocationFull":"Austin, TX",
            "formattedRelativeTime":"11 hours ago"
        },

        {  
            "jobtitle":"Ruby Developer",
            "company":"Facebook inc",
            "city":"Austin",
            "state":"TX",
            "country":"US",
            "formattedLocation":"Soweto, TX",
            "source":"Dice",
            "date":"Mon, 02 Aug 2017 16:21:00 GMT",
            "snippet": `looking for a midlevel Ruby and Rails developer,
              HTML, JavaScript, AJAX, Struts, Ruby Rails, JSx) desirable.`,
            "url":"http://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203",
            "onmousedown":"indeed_clk(this, '0000');",
            "latitude":30.27127,
            "longitude":-97.74103,
            "jobkey":"12346",
            "sponsored":false,
            "expired":false,
            "indeedApply":true,
            "formattedLocationFull":"Austin, TX",
            "formattedRelativeTime":"2 days ago"
        },
        {  
            "jobtitle":"Javascript Developer",
            "company":"Oasis Inc",
            "city":"Austin",
            "state":"TX",
            "country":"US",
            "formattedLocation":"Austin, TX",
            "source":"Dice",
            "date":"Mon, 02 Jan 2018 05:24:00 GMT",
            "snippet": `looking for a Javascript Developer,
              HTML, JavaScript, AJAX, Struts, Struts2, JSF) desirable. Familiarity with
              React and the Angular...`,
            "url":"http://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203",
            "onmousedown":"indeed_clk(this, '0000');",
            "latitude":30.27127,
            "longitude":-97.74103,
            "jobkey":"12347",
            "sponsored":false,
            "expired":false,
            "indeedApply":true,
            "formattedLocationFull":"Austin, TX",
            "formattedRelativeTime":"3 hours ago"
        },
        {  
            "jobtitle":"Golang Developer",
            "company":"Go corps",
            "city":"Austin",
            "state":"TX",
            "country":"US",
            "formattedLocation":"Austin, TX",
            "source":"Dice",
            "date":"Mon, 02 oct 2017 16:21:00 GMT",
            "snippet": `looking for an object-oriented GOlang developer,
              HTML, JavaScript, AJAX, Css, Struts2, JSF) desirable.`,
            "url":"http://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203",
            "onmousedown":"indeed_clk(this, '0000');",
            "latitude":30.27127,
            "longitude":-97.74103,
            "jobkey":"12348",
            "sponsored":false,
            "expired":false,
            "indeedApply":true,
            "formattedLocationFull":"Austin, TX",
            "formattedRelativeTime":"23 hours ago"
        }
    ]
}